os: osx
osx_image: xcode11

env:
  - TRAVIS_TAG="Deploy-2017.2.0f3" PROJECT_NAME="UnityExamplePackage" UNITY_PROJECT_PATH="UnityExample" DEPLOY_UNITYPACKAGE="path set in deploy script"
  - ANDROID_SDK_VERSION=4333796

cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

before_install:
  PKG_OS='darwin';
  export ANDROID_HOME="${HOME}/android-sdk";
  export PATH=$PATH:"${ANDROID_HOME}/tools/bin";
  mkdir $ANDROID_HOME 
  - chmod a+x scripts/*.sh
  - chmod a+x ./*.sh

install:
  # SDK Tools.
  - >
    curl -o sdk.zip "https://dl.google.com/android/repository/sdk-tools-${PKG_OS}-${ANDROID_SDK_VERSION}.zip" &&
    unzip -q sdk.zip -d $ANDROID_HOME;
  - yes | sdkmanager --licenses > /dev/null
  - sdkmanager 'build-tools;27.0.0' 'platforms;android-27' > /dev/null
  - cat /etc/hosts
  - ./scripts/install-unity.sh

script:
- make unitypackage
# - ./build.sh

after_success:
# - ./scripts/export-unity-package.sh

before_deploy:
- DEPLOY_UNITYPACKAGE="$(ls -a release/*.zip | head -n 1)"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $DEPLOY_UNITYPACKAGE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true 