language: objective-c
osx_image: xcode11
matrix:
  include:
    - language: android
rvm:
- 2.2 #see before_install for getting RVM stable.

env:
- TRAVIS_TAG="Deploy-2017.2.0f3" PROJECT_NAME="UnityExamplePackage" UNITY_PROJECT_PATH="UnityExample" DEPLOY_UNITYPACKAGE="path set in deploy script"

cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE


before_install:
- brew tap caskroom/cask
- brew cask install android-sdk
- export ANDROID_HOME=/usr/local/share/android-sdk
- yes | sdkmanager --licenses && sdkmanager --update
- chmod a+x scripts/*.sh
- chmod a+x ./*.sh

install:
- cat /etc/hosts
- ./scripts/install-unity.sh

script:
- make unitypackage
# - ./build.sh

after_success:
# - ./scripts/export-unity-package.sh

before_deploy:
- DEPLOY_UNITYPACKAGE="$(ls -a release/*.zip | head -n 1)"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $DEPLOY_UNITYPACKAGE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true 