os: osx
osx_image: xcode11

env:
  - TRAVIS_TAG="Deploy-2017.2.0f3" PROJECT_NAME="UnityExamplePackage" UNITY_PROJECT_PATH="UnityExample" DEPLOY_UNITYPACKAGE="path set in deploy script"
  - ANDROID_SDK_VERSION=4333796

cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

before_install:
  - chmod a+x scripts/*.sh
  - chmod a+x ./*.sh

install:
  # SDK Tools.
  - curl -o android-sdk.zip https://dl.google.com/android/repository/sdk-tools-darwin-4333796.zip
  - unzip android-sdk.zip
  - export ANDROID_HOME=$PWD/android-sdk-macosx
  - export PATH=$PATH:$ANDROID_HOME/tools
  - export PATH=$PATH:$ANDROID_HOME/platform-tools
  - export JAVA_HOME=$(/usr/libexec/java_home)
  - echo "y" | android update sdk --no-ui --all --filter tool,platform-tool,android-28,build-tools-28.0.3
  - cat /etc/hosts
  - ./scripts/install-unity.sh

script:
- make unitypackage
# - ./build.sh

after_success:
# - ./scripts/export-unity-package.sh

before_deploy:
- DEPLOY_UNITYPACKAGE="$(ls -a release/*.zip | head -n 1)"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $DEPLOY_UNITYPACKAGE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true