os: osx
osx_image: xcode9.3

before_install:
  - brew tap caskroom/cask
  - brew cask install android-sdk
  - export ANDROID_HOME=/usr/local/share/android-sdk
  - yes | sdkmanager --licenses && sdkmanager --update
  - chmod a+x ./Tools/install.sh
install:
  - ./Tools/install.sh
script:
  - make unitypackage
