// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.IO;
using System.Net;

namespace LeanplumSDK
{
	public interface ISocketUtils
	{
		bool AreSocketsAvailable { get; }
		bool IsDataAvailable (Stream stream);
		Stream CreateNetworkStream (ISocket socket, bool ownsSocket);
		ISocket CreateSocket (IPAddress address);
		ISocketAsyncEventArgs CreateSocketAsyncEventArgs ();
		ISocketAsyncEventArgs CreateSocketAsyncEventArgs (EventArgs e);
		ITcpClient CreateTcpClient (string host, int port);
	}

	public interface ISocket
	{
		void Bind (IPEndPoint endpoint);
		void Listen (int backlog);
		void AcceptAsync (ISocketAsyncEventArgs args);
		void Close ();
		void Shutdown ();
		EndPoint LocalEndPoint { get; }
		EndPoint RemoteEndPoint { get; }
	}

	public interface ISocketAsyncEventArgs
	{
		object UserToken { get; set; }
		bool IsSuccess ();
		ISocket AcceptSocket { get; set; }
		event EventHandler<EventArgs> Completed;
	}

	public interface ITcpClient
	{
		EndPoint GetLocalEndpoint ();
		EndPoint GetRemoteEndpoint ();
		Stream GetStream ();
		void Close ();
	}

	public static class SocketUtilsFactory
	{
		private static ISocketUtils utils = new DisabledSocketUtils();

		public static ISocketUtils Utils {
			get {
					return utils;
			}
			set {
					utils = value;
			}
		}
	}

	public class DisabledSocketUtils : ISocketUtils
	{
		public bool AreSocketsAvailable
		{
			get { return false; }
		}
		
		public bool IsDataAvailable (Stream stream)
		{
			return false;
		}
		
		public Stream CreateNetworkStream (ISocket socket, bool ownsSocket)
		{
			return null;
		}
		
		public ISocket CreateSocket (IPAddress address)
		{
			return null;
		}
		
		public ISocketAsyncEventArgs CreateSocketAsyncEventArgs ()
		{
			return null;
		}
		
		public ISocketAsyncEventArgs CreateSocketAsyncEventArgs (EventArgs e)
		{
			return null;
		}
		
		public ITcpClient CreateTcpClient (string host, int port)
		{
			return null;
		}
	}
}

